service: bot
frameworkVersion: "3"

useDotenv: true

provider: 
  name: yandex-cloud 
  runtime: nodejs16 
  httpApi: 
    payload: '1.0' 
  
functions: 
  echo:
    environment:
      TELEGRAM_BOT_TOKEN: ${env:BOT_TOKEN}
    handler: dist/index.echoHandler 
    memorySize: 128 
    timeout: 3

plugins: 
  - "@yandex-cloud/serverless-plugin"
  - "serverless-dotenv-plugin"
  
package: 
  patterns: 
  - '!**' 
  - package.json 
  - package-lock.json 
  - dist/*.js